spring:
  application:
    name: zuul-edge-server
  profiles:
    active: localhost

info:
  component: Zuul Edge Server

---
spring:
  profiles: localhost


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

server:
  port: 8762

zuul:
  routes:
    user-service:
      path: /api/1.0/user/**
      serviceId: user-service
      strip-prefix: false

---
spring:
  profiles: stage

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

zuul:
  routes:
    user-service:
      path: /api/1.0/user/**
      serviceId: user-service
      strip-prefix: false